# Generated by Django 3.2.25 on 2026-01-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislog',
            name='explanation_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysislog',
            name='explanation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
