# Generated by Django 3.2.25 on 2026-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetectionApp', '0002_auto_20260131_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislog',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
